### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vegarringdal** [aurelia-ui-toolkits/aurelia-v-grid#44]
Improve:

- [x] set/get columns function, so its easier to use
- [x] option to disable the attributes the simple columns adds, so you can have full control here too if you want
- [x] add simple multisort function that enables doing this by code very simple

**Comment by adriatic** [comment]
I love to see the care you show for your v-grid baby

**Comment by vegarringdal** [comment]
@adriatic 
:smile: Noticed when I did a gist that manually setting columns after was not very good, so this will work kinda like this now:

```
var columnsOption1 = [
    {
      colWidth:122,
      colField:"name"
    },
    {
      colWidth:122,
      colField:"bool"
    },
    {
      colWidth:122,
      colField:"number"
    }]

this.myGrid.ctx.setColumns(this.columnsOption2)
this.myGrid.ctx.reGenerateColumns();

```

optons when setting will be:

```
colWidth: 100,
      colRowTemplate: null,
      colHeaderTemplate: null,
      colField: "row attribute",
      colHeaderName: "test of header",
      colAddLabelAttributes: "",
      colAddFilterAttributes: "",
      colAddRowAttributes: "",
      colSort: null,
      colFilter: true/true
      colFilterTop: false/true
      colCss: "",
      colType: "checkbox" /text or image
```
